[FIX] mrp: Fix memory error
Due to more workorder per workcenter it breaking and
leading to memory error during fetching order_ids.

```
sagu_3768740=> select count(id) from mrp_workorder group by workcenter_id order by count(id) desc limit 10;
 count
-------
 72627
 70848
 28157
 27858
 26583
 10674
 10205
  9810
  9809
  9667
(10 rows)
```

```
Traceback (most recent call last):
  File "/tmp/tmp4ps1zh4l/migrations/base/tests/test_mock_crawl.py", line 333, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmp4ps1zh4l/migrations/base/tests/test_mock_crawl.py", line 346, in mock_action
    return self.mock_act_window(action)
  File "/tmp/tmp4ps1zh4l/migrations/base/tests/test_mock_crawl.py", line 506, in mock_act_window
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmp4ps1zh4l/migrations/base/tests/test_mock_crawl.py", line 625, in mock_view_kanban
    self.mock_web_search_read(model, view, [domain], fields_list)
  File "/tmp/tmp4ps1zh4l/migrations/base/tests/test_mock_crawl.py", line 691, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80, order=filter_order(model))
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 5783, in search_read
    return records._read_format(fnames=fields, **read_kwargs)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3748, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 6684, in __getitem__
    return self._fields[key].__get__(self)
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 1746, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 1917, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/19.0/addons/mail/models/mail_thread.py", line 483, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 4953, in _compute_field_value
    determine(field.compute, self)
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 81, in determine
    return needle(*args)
  File "/home/odoo/src/odoo/19.0/addons/mrp/models/mrp_workcenter.py", line 98, in _compute_kanban_dashboard_graph
    load_data = self._get_workcenter_load_per_week(week_range, date_start, date_stop)
  File "/home/odoo/src/odoo/19.0/addons/mrp/models/mrp_workcenter.py", line 137, in _get_workcenter_load_per_week
    if not self.order_ids:
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields_relational.py", line 931, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields_relational.py", line 75, in __get__
    super().__get__(remaining, owner)
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 1702, in __get__
    recs._fetch_field(self)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3773, in _fetch_field
    self.fetch(fnames)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3813, in fetch
    fetched = self._fetch_query(query, fields_to_fetch)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3941, in _fetch_query
    field.read(fetched)
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields_relational.py", line 947, in read
    lines = comodel.search_fetch(domain, field_names)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 1418, in search_fetch
    return self._fetch_query(query, fields_to_fetch)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3918, in _fetch_query
    rows = self.env.execute_query(query.select(*sql_terms))
  File "/home/odoo/src/odoo/19.0/odoo/orm/environments.py", line 534, in execute_query
    self.cr.execute(query)
  File "/home/odoo/src/odoo/19.0/odoo/tests/test_cursor.py", line 79, in execute
    return self._cursor.execute(*args, **kwargs)
  File "/home/odoo/src/odoo/19.0/odoo/sql_db.py", line 433, in execute
    self._obj.execute(query, params)
psycopg2.DatabaseError: out of memory for query result
```

opw-5472114
upg-3862178