[FIX] repair: handle missing inventory loss location
Currently, an error occurs when user tries to create a new warehouse when
Inventory loss stock location is not present.

Steps to replicate:
- Install repairs and enable Storage Locations in settings.
- Go to `Inventory > Configuration > Locations`, open `Inventory Adjustment`.
- Change the `Location Type` to `Internal`(anything other than `Inventory Loss`)
- Navigate to Warehouses and try to create a new one.

Error:
```
  File /home/odoo/src/odoo/19.0/addons/stock/models/stock_warehouse.py, line 142, in create
    new_vals = warehouse._create_or_update_sequences_and_picking_types()
  File /home/odoo/src/odoo/19.0/addons/stock/models/stock_warehouse.py, line 373, in _create_or_update_sequences_and_picking_types
    create_data, max_sequence = self._get_picking_type_create_values(max_sequence)
  File /home/odoo/src/odoo/19.0/addons/repair/models/stock_warehouse.py, line 30, in _get_picking_type_create_values
    scrap_location_id = self.env['stock.location'].search_read([('usage', '=', 'inventory'), ('company_id', 'in', [self.company_id.id, False])], fields=['id'], limit=1)[0].get('id')
IndexError: list index out of range
```

Cause:
- Since the user changed the location type of `Inventory adjustment`, the
 `search_read()` [1] returned no results and attempting to access its first
  element causes the error.

Solution:
- Assign value to `default_remove_location_dest_id` only if an inventory loss
  location exists.

[1]: https://github.com/odoo/odoo/blob/62b9f7a81e8d742508d6c80434bb4caf78f9dc65/addons/repair/models/stock_warehouse.py#L30

sentry-7169389190